# [tool.cibuildwheel]
# platforms = [
#     "manylinux_x86_64",
#     "manylinux_aarch64",
#     "macosx_arm64",
#     "windows"
# ]
# build = ["cp310-*", "cp311-*", "cp312-*"]

# [tool.cibuildwheel.manylinux_x86_64]
# python-versions = ["3.10", "3.11", "3.12"]

# [tool.cibuildwheel.manylinux_aarch64]
# python-versions = ["3.10", "3.11", "3.12"]

# [tool.cibuildwheel.musllinux_x86_64]
# python-versions = ["3.10", "3.11", "3.12"]

# [tool.cibuildwheel.musllinux_aarch64]
# python-versions = ["3.10", "3.11", "3.12"]

# [tool.cibuildwheel.macosx_arm64]
# python-versions = ["3.10", "3.11", "3.12"]

# [tool.cibuildwheel.windows]
# python-versions = ["3.10", "3.11", "3.12"]

# [tool.cibuildwheel]
# skip = ["cp36-*", "cp37-*", "cp38-*", "cp39-*", "*-win32", "*-manylinux_i686"]
# build = ["cp310-*", "cp311-*", "cp312-*"]

# # Linux x86_64 and aarch64
# [[tool.cibuildwheel.linux]]
# archs = ["x86_64", "aarch64"]

# # macOS aarch64
# [[tool.cibuildwheel.macos]]
# archs = ["arm64"]

# # Windows
# [[tool.cibuildwheel.windows]]
# archs = ["AMD64"]
