[tool.poetry]
name = "llama-cpp-cffi"
version = "0.1.7"
description = "Python binding for llama.cpp using cffi"
homepage = "https://github.com/tangledgroup/llama-cpp-cffi"
repository = "https://github.com/tangledgroup/llama-cpp-cffi"
authors = ["Marko Tasic <mtasic85@gmail.com>", "Tangled Group, Inc <info@tangledgroup.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "llama"}]
include = [{path = "llama/*.so"}]

[tool.poetry.dependencies]
python = "^3.10"
attrs = "^23.2.0"
huggingface-hub = "^0.24.1"
cffi = "^1.16.0"
setuptools = "^71.0.3"
psutil = "^6.0.0"
transformers = "^4.43.1"
jinja2 = "^3.1.4"
sentencepiece = "^0.2.0"
protobuf = "^5.27.2"
numba = "^0.60.0"
openai = {version = "^1.35.15", optional = true}
aiohttp = {extras = ["speedups"], version = "^3.9.5", optional = true}
uvloop = {version = "^0.19.0", optional = true}

[tool.poetry.extras]
openai = ["openai", "aiohttp"]
uvloop = ["uvloop"]

[tool.poetry.group.dev.dependencies]
cibuildwheel = "^2.19.2"

[tool.poetry.scripts]
build = "scripts.build:build"
clean = "scripts.clean:clean"

[tool.poetry.build]
script = "scripts/build.py"

[tool.cibuildwheel]

[tool.cibuildwheel.linux]
build-frontend = "build"
before-build = """
pip install poetry

if [[ $AUDITWHEEL_PLAT == manylinux* ]]; then
    dnf update -y
    dnf install -y epel-release
    dnf install -y unzip p7zip p7zip-plugins
else
    apk -U add upx unzip 7zip
fi
"""
skip = ["cp36-*", "cp37-*", "cp38-*", "cp39-*", "pp37-*", "pp38-*", "pp39-*", "*i686"]
# skip = ["cp36-*", "cp37-*", "cp38-*", "cp39-*", "cp310-*", "cp311-*", "pp37-*", "pp38-*", "pp39-*", "pp310-*", "*i686"]
manylinux-x86_64-image = "quay.io/pypa/manylinux_2_28_x86_64:latest"
manylinux-aarch64-image = "quay.io/pypa/manylinux_2_28_aarch64:latest"
manylinux-pypy_x86_64-image = "quay.io/pypa/manylinux_2_28_x86_64:latest"
manylinux-pypy_aarch64-image = "quay.io/pypa/manylinux_2_28_aarch64:latest"
musllinux-x86_64-image = "quay.io/pypa/musllinux_1_2_x86_64:latest"
musllinux-aarch64-image = "quay.io/pypa/musllinux_1_2_aarch64:latest"
build-verbosity=3
repair-wheel-command = """
for file in {wheel}; do
    tempdir=$(mktemp -d)
    unzip -d "$tempdir" "$file"
    (cd "$tempdir" && 7z a -tzip -mx=9 -mfb=258 -mpass=15 -mmt=on "{dest_dir}/$(basename $file)" .)
    rm -rf "$tempdir"
done
"""
environment = {"LD_LIBRARY_PATH" = "/project/cuda-12.5.1/dist/lib64:/project/cuda-12.5.1/dist/targets/x86_64-linux/lib:/project/cuda-12.5.1/dist/lib64/stubs:$LD_LIBRARY_PATH", "CUDA_HOME" = "/project/cuda-12.5.1/dist"}

[tool.cibuildwheel.pyodide]

[build-system]
requires = ["poetry-core", "cffi", "setuptools"]
build-backend = "poetry.core.masonry.api"
