name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_BUILD: cp310-* cp311-* cp312-*
          CIBW_ARCHS_LINUX: x86_64 aarch64
          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_ARCHS_WINDOWS: AMD64
          CIBW_SKIP: "*-win32 *-manylinux_i686"
          CIBW_BEFORE_BUILD: poetry build

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_pyodide:
    name: Build for Pyodide
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry and Pyodide
        run: |
          pip install poetry pyodide-build

      - name: Build for Pyodide
        run: |
          pyodide build

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*.whl